"""
ollama_engine.py
Legge PDF progetto e chiama Ollama (qwen2.5:14b) per analisi cascata.
Include geometry_changes per modificare il modello 3D.
"""

import json
import re
import httpx
from pathlib import Path

OLLAMA_URL = "https://uselessly-decompose-chomp.ngrok-free.dev/api/generate"
MODEL      = "qwen2.5:14b"

SYSTEM_PROMPT = """You are a senior systems engineer specialized in space payload verification and validation (V&V).

You receive the full state of a space project as context (requirements, subsystems, V&V evidence, NCRs, ECSS checklist, system constraints).

The 3D model of the payload has these subsystems with their geometry IDs:
- "structure": primary box structure of the satellite body
- "optical": cylindrical telescope tube on top
- "thermal": flat thermal control panel
- "mechanical": base mechanical structure plate
- "solar": solar panels (left and right wings)
- "startracker": spherical star tracker sensor
- "dataproc": data processing unit box

When the user proposes a change request, your job is to:
1. Identify ALL cascading problems generated by the change
2. For each problem specify: what breaks, why, which requirement/subsystem is affected
3. Identify missing tests or ECSS validation activities that become mandatory
4. Extract geometry changes to update the 3D model visually
5. DO NOT propose solutions — only identify problems and their root cause

For geometry_changes use these rules:

operation types:
- "scale"  → resize a part (use scale_factor and dimension)
- "remove" → completely remove a part from the model
- "add"    → add a new part (describe it)

part_id values (use these exact strings):
- "structure_body"   → main satellite box
- "optical_tube"     → telescope cylinder
- "optical_baffle"   → baffle ring on top of telescope
- "thermal_panel"    → thermal control flat panel
- "thermal_radiator" → side radiator
- "mechanical_base"  → base plate
- "solar_right"      → right solar panel wing
- "solar_left"       → left solar panel wing
- "solar_conn_right" → right solar panel connector
- "solar_conn_left"  → left solar panel connector
- "startracker_body" → star tracker sphere
- "dataproc_box"     → data processing box

For scale operations:
- scale_factor 1.0 = no change, 1.4 = 40% larger, 0.7 = 30% smaller
- dimension: "height", "width", "depth", "radius", "all"
- direction: "up", "down", "left", "right", "uniform"

Respond ONLY in valid JSON with this exact structure:
{
  "change_summary": "brief description of what was changed",
  "geometry_changes": [
    {
      "operation": "remove",
      "part_id": "solar_right",
      "subsystem": "solar",
      "description": "right solar panel removed"
    },
    {
      "operation": "scale",
      "part_id": "structure_body",
      "subsystem": "structure",
      "dimension": "height",
      "scale_factor": 1.4,
      "direction": "down",
      "description": "structure extended downward 40%"
    }
  ],
  "cascade_issues": [
    {
      "id": "ISSUE-001",
      "severity": "critical|major|minor",
      "subsystem": "affected subsystem id",
      "requirement": "affected requirement id or null",
      "title": "short title of the problem",
      "description": "detailed explanation of why this is a problem",
      "type": "constraint_violation|missing_test|ncr_required|reanalysis_required"
    }
  ],
  "missing_tests": [
    {
      "ecss_standard": "ECSS-X-XX-XXX",
      "clause": "§X.X",
      "activity": "description of required test",
      "reason": "why this test is now required"
    }
  ],
  "affected_requirements": ["L1-XXX-001"],
  "affected_subsystems": ["subsystem_id"],
  "go_nogo_impact": "GO|GO_WITH_CONSTRAINTS|NO_GO",
  "confidence_delta": -15,
  "managerial_summary": "Plain language summary for program manager: what is the business impact of this change, which milestone is at risk, what needs to happen before CDR/launch, is customer notification required."
}

Be precise, technical, and conservative. If in doubt, flag the issue."""


def load_pdf_as_text(pdf_path: Path) -> str:
    try:
        from pypdf import PdfReader
        reader = PdfReader(str(pdf_path))
        text = ""
        for page in reader.pages:
            text += page.extract_text() + "\n"
        return text
    except ImportError:
        raise ImportError("Installa pypdf: pip install pypdf")


def build_prompt(project_context: str, change_request: str) -> str:
    return f"""PROJECT CONTEXT:
{project_context}

---
CHANGE REQUEST:
{change_request}

---
Analyze all cascading problems and geometry changes generated by this change request.
Respond only in valid JSON."""


def call_ollama(prompt: str, system: str = SYSTEM_PROMPT) -> str:
    payload = {
        "model": MODEL,
        "prompt": prompt,
        "system": system,
        "stream": True,
        "options": {
            "temperature": 0.1,
            "top_p": 0.9,
            "num_predict": 2048,
        }
    }

    full_response = ""
    with httpx.stream("POST", OLLAMA_URL, json=payload, timeout=180.0) as r:
        r.raise_for_status()
        for line in r.iter_lines():
            if line:
                try:
                    chunk = json.loads(line)
                    full_response += chunk.get("response", "")
                    if chunk.get("done"):
                        break
                except json.JSONDecodeError:
                    continue

    return full_response


def extract_json(raw: str) -> dict:
    try:
        return json.loads(raw.strip())
    except json.JSONDecodeError:
        pass

    match = re.search(r"```json\s*(.*?)\s*```", raw, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass

    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError:
            pass

    return {
        "error": "JSON parsing failed",
        "raw_response": raw,
        "geometry_changes": [],
        "cascade_issues": [],
        "missing_tests": [],
        "affected_requirements": [],
        "affected_subsystems": [],
        "go_nogo_impact": "NO_GO",
        "confidence_delta": -50,
    }


def analyze_change(pdf_path: Path, change_request: str) -> dict:
    print(f"Lettura PDF: {pdf_path}")
    context = load_pdf_as_text(pdf_path)
    print(f"Contesto: {len(context)} caratteri")
    print(f"Cambio richiesto: {change_request}")
    print(f"Chiamata a {MODEL}...")

    prompt = build_prompt(context, change_request)
    raw    = call_ollama(prompt)
    result = extract_json(raw)

    print(f"Issues: {len(result.get('cascade_issues', []))}")
    print(f"Geometry changes: {len(result.get('geometry_changes', []))}")
    return result


if __name__ == "__main__":
    pdf = Path(__file__).parent / "projects" / "IRIS-3" / "main" / "IRIS3_main.pdf"

    if not pdf.exists():
        print("PDF non trovato — esegui prima: python mock_data/generate_pdf.py")
        exit(1)

    change = "The structure must be longer downward by 40% to accommodate a larger battery pack."
    result = analyze_change(pdf, change)

    out = Path(__file__).parent / "projects" / "IRIS-3" / "analysis_test.json"
    with open(out, "w") as f:
        json.dump(result, f, indent=2)

    print(json.dumps(result, indent=2))